version: '3.8'

services:
  app:
    image: ahmedsherif98/magasin-console-app:latest
    container_name: magasinconsole-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: "Host=db;Port=5432;Database=magasindb;Username=postgres;Password=postgres"
    ports:
      - "8090:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magasindb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magasinuser"]
      interval: 30s
      timeout: 5s
      retries: 5
